name: flutter_localizations_tk

environment:
  sdk: ^3.8.0-0

# resolution: workspace

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  #
  # For detailed instructions, refer to:
  # https://github.com/flutter/flutter/blob/main/docs/infra/Updating-dependencies-in-Flutter.md

  flutter:
    sdk: flutter
  intl: # You must keep the name 'intl' to override the default dependency
    git:
      url: https://github.com/DowranRowshenow/i18n_tk.git 
      # Specify the subdirectory where the pubspec.yaml lives inside the monorepo
      path: pkgs/intl 
      ref: main
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

executables:
  # The user command: flutter pub run your_localizations_plugin:gen-l10n-tk
  gen_l10n_tk: gen_l10n_tk
  post_process_l10n: post_process_l10n
# PUBSPEC CHECKSUM: c2j4ng
